-- ============================================
-- Supabase Schema for SmartBreaker
-- Run this in Supabase SQL Editor
-- ============================================

-- Django auth tables (required for permissions/groups)
CREATE TABLE auth_group (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE auth_permission (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    content_type_id INT NOT NULL,
    codename VARCHAR(100) NOT NULL,
    UNIQUE (content_type_id, codename)
);

-- ============================================
-- Table: accounts_user
-- ============================================
CREATE TABLE accounts_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password VARCHAR(128) NOT NULL,
    last_login TIMESTAMPTZ,
    is_superuser BOOLEAN NOT NULL DEFAULT FALSE,
    email VARCHAR(254) NOT NULL UNIQUE,
    phone VARCHAR(20) NOT NULL DEFAULT '',
    role VARCHAR(20) NOT NULL CHECK (role IN ('admin', 'technician', 'home_user')),
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    is_staff BOOLEAN NOT NULL DEFAULT FALSE,
    must_set_password BOOLEAN NOT NULL DEFAULT TRUE,
    otp_hash VARCHAR(128),
    otp_expires_at TIMESTAMPTZ,
    otp_last_sent_at TIMESTAMPTZ,
    reset_code_hash VARCHAR(128),
    reset_code_expires_at TIMESTAMPTZ,
    reset_code_last_sent_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Junction: User <-> Group (M2M)
CREATE TABLE accounts_user_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES accounts_user(id) ON DELETE CASCADE,
    group_id INT NOT NULL REFERENCES auth_group(id) ON DELETE CASCADE,
    UNIQUE (user_id, group_id)
);

-- Junction: User <-> Permission (M2M)
CREATE TABLE accounts_user_user_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES accounts_user(id) ON DELETE CASCADE,
    permission_id INT NOT NULL REFERENCES auth_permission(id) ON DELETE CASCADE,
    UNIQUE (user_id, permission_id)
);

-- ============================================
-- Table: accounts_registrationrequest
-- ============================================
CREATE TABLE accounts_registrationrequest (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL,
    phone VARCHAR(20) NOT NULL DEFAULT '',
    role VARCHAR(20) NOT NULL CHECK (role IN ('home_user', 'technician')),
    status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'denied')),
    reviewed_by_id BIGINT REFERENCES accounts_user(id) ON DELETE SET NULL,
    reviewed_at TIMESTAMPTZ,
    created_user_id BIGINT UNIQUE REFERENCES accounts_user(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================
-- Table: organizations_organization
-- ============================================
CREATE TABLE organizations_organization (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    latitude DECIMAL(9, 6) NOT NULL,
    longitude DECIMAL(9, 6) NOT NULL,
    owner_id BIGINT NOT NULL REFERENCES accounts_user(id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'active')),
    reviewed_by_id BIGINT REFERENCES accounts_user(id) ON DELETE SET NULL,
    reviewed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================
-- Indexes for performance
-- ============================================
CREATE INDEX idx_user_email ON accounts_user(email);
CREATE INDEX idx_user_role ON accounts_user(role);
CREATE INDEX idx_registration_reviewed_by ON accounts_registrationrequest(reviewed_by_id);
CREATE INDEX idx_registration_created_user ON accounts_registrationrequest(created_user_id);
CREATE INDEX idx_org_owner ON organizations_organization(owner_id);
CREATE INDEX idx_org_reviewed_by ON organizations_organization(reviewed_by_id);
CREATE INDEX idx_org_status ON organizations_organization(status);
